with-expecter: True
filename: "{{ .InterfaceName }}_mock.go"
packages:
  github.com/BoltzExchange/boltz-client/onchain:
    interfaces:
      Wallet:
      TxProvider:
      BlockProvider:
      TxBroadcaster:
  github.com/BoltzExchange/boltz-client/autoswap:
    config:
      dir: autoswap
      inpackage: True
    interfaces:
      RpcProvider:
  github.com/BoltzExchange/boltz-client/lightning:
    interfaces:
      LightningNode:
