with-expecter: True
filename: "{{ .InterfaceName }}_mock.go"
dir: ./internal/mocks/{{.PackageName}}
packages:
  github.com/BoltzExchange/boltz-client/v2/internal/onchain:
    interfaces:
      Wallet:
      TxProvider:
      BlockProvider:
  github.com/BoltzExchange/boltz-client/v2/internal/autoswap:
    config:
      dir: ./internal/autoswap
      inpackage: True
    interfaces:
      RpcProvider:
  github.com/BoltzExchange/boltz-client/v2/internal/lightning:
    interfaces:
      LightningNode:
