with-expecter: True
filename: "{{ .InterfaceName }}_mock.go"
packages:
  github.com/BoltzExchange/boltz-client/onchain:
    interfaces:
      Wallet:
      TxProvider:
  github.com/BoltzExchange/boltz-client/autoswap:
    config:
      dir: autoswap
      inpackage: True
    interfaces:
      RpcProvider:
