// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc.proto

package boltzrpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetInfoRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInfoRequest) Reset()         { *m = GetInfoRequest{} }
func (m *GetInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetInfoRequest) ProtoMessage()    {}
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{0}
}

func (m *GetInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfoRequest.Unmarshal(m, b)
}
func (m *GetInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfoRequest.Merge(m, src)
}
func (m *GetInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetInfoRequest.Size(m)
}
func (m *GetInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfoRequest proto.InternalMessageInfo

type GetInfoResponse struct {
	Symbol               string   `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	LndPubkey            string   `protobuf:"bytes,2,opt,name=lnd_pubkey,json=lndPubkey,proto3" json:"lnd_pubkey,omitempty"`
	BlockHeight          uint32   `protobuf:"varint,3,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	PendingSwaps         []string `protobuf:"bytes,4,rep,name=pending_swaps,json=pendingSwaps,proto3" json:"pending_swaps,omitempty"`
	PendingReverseSwaps  []string `protobuf:"bytes,5,rep,name=pending_reverse_swaps,json=pendingReverseSwaps,proto3" json:"pending_reverse_swaps,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInfoResponse) Reset()         { *m = GetInfoResponse{} }
func (m *GetInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetInfoResponse) ProtoMessage()    {}
func (*GetInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{1}
}

func (m *GetInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfoResponse.Unmarshal(m, b)
}
func (m *GetInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfoResponse.Merge(m, src)
}
func (m *GetInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetInfoResponse.Size(m)
}
func (m *GetInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfoResponse proto.InternalMessageInfo

func (m *GetInfoResponse) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *GetInfoResponse) GetLndPubkey() string {
	if m != nil {
		return m.LndPubkey
	}
	return ""
}

func (m *GetInfoResponse) GetBlockHeight() uint32 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *GetInfoResponse) GetPendingSwaps() []string {
	if m != nil {
		return m.PendingSwaps
	}
	return nil
}

func (m *GetInfoResponse) GetPendingReverseSwaps() []string {
	if m != nil {
		return m.PendingReverseSwaps
	}
	return nil
}

type GetSwapInfoRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSwapInfoRequest) Reset()         { *m = GetSwapInfoRequest{} }
func (m *GetSwapInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetSwapInfoRequest) ProtoMessage()    {}
func (*GetSwapInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{2}
}

func (m *GetSwapInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSwapInfoRequest.Unmarshal(m, b)
}
func (m *GetSwapInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSwapInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetSwapInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSwapInfoRequest.Merge(m, src)
}
func (m *GetSwapInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetSwapInfoRequest.Size(m)
}
func (m *GetSwapInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSwapInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSwapInfoRequest proto.InternalMessageInfo

func (m *GetSwapInfoRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type SwapInfo struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	PrivateKey           string   `protobuf:"bytes,3,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	Preimage             string   `protobuf:"bytes,4,opt,name=preimage,proto3" json:"preimage,omitempty"`
	RedeemScript         string   `protobuf:"bytes,5,opt,name=redeem_script,json=redeemScript,proto3" json:"redeem_script,omitempty"`
	Invoice              string   `protobuf:"bytes,6,opt,name=invoice,proto3" json:"invoice,omitempty"`
	LockupAddress        string   `protobuf:"bytes,7,opt,name=lockup_address,json=lockupAddress,proto3" json:"lockup_address,omitempty"`
	ExpectedAmount       int64    `protobuf:"varint,8,opt,name=expected_amount,json=expectedAmount,proto3" json:"expected_amount,omitempty"`
	TimeoutBlockHeight   uint32   `protobuf:"varint,9,opt,name=timeout_block_height,json=timeoutBlockHeight,proto3" json:"timeout_block_height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SwapInfo) Reset()         { *m = SwapInfo{} }
func (m *SwapInfo) String() string { return proto.CompactTextString(m) }
func (*SwapInfo) ProtoMessage()    {}
func (*SwapInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{3}
}

func (m *SwapInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SwapInfo.Unmarshal(m, b)
}
func (m *SwapInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SwapInfo.Marshal(b, m, deterministic)
}
func (m *SwapInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SwapInfo.Merge(m, src)
}
func (m *SwapInfo) XXX_Size() int {
	return xxx_messageInfo_SwapInfo.Size(m)
}
func (m *SwapInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SwapInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SwapInfo proto.InternalMessageInfo

func (m *SwapInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SwapInfo) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *SwapInfo) GetPrivateKey() string {
	if m != nil {
		return m.PrivateKey
	}
	return ""
}

func (m *SwapInfo) GetPreimage() string {
	if m != nil {
		return m.Preimage
	}
	return ""
}

func (m *SwapInfo) GetRedeemScript() string {
	if m != nil {
		return m.RedeemScript
	}
	return ""
}

func (m *SwapInfo) GetInvoice() string {
	if m != nil {
		return m.Invoice
	}
	return ""
}

func (m *SwapInfo) GetLockupAddress() string {
	if m != nil {
		return m.LockupAddress
	}
	return ""
}

func (m *SwapInfo) GetExpectedAmount() int64 {
	if m != nil {
		return m.ExpectedAmount
	}
	return 0
}

func (m *SwapInfo) GetTimeoutBlockHeight() uint32 {
	if m != nil {
		return m.TimeoutBlockHeight
	}
	return 0
}

type ReverseSwapInfo struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	PrivateKey           string   `protobuf:"bytes,3,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	Preimage             string   `protobuf:"bytes,4,opt,name=preimage,proto3" json:"preimage,omitempty"`
	RedeemScript         string   `protobuf:"bytes,5,opt,name=redeem_script,json=redeemScript,proto3" json:"redeem_script,omitempty"`
	Invoice              string   `protobuf:"bytes,6,opt,name=invoice,proto3" json:"invoice,omitempty"`
	ClaimAddress         string   `protobuf:"bytes,7,opt,name=claim_address,json=claimAddress,proto3" json:"claim_address,omitempty"`
	OnchainAmount        int64    `protobuf:"varint,8,opt,name=onchain_amount,json=onchainAmount,proto3" json:"onchain_amount,omitempty"`
	TimeoutBlockHeight   uint32   `protobuf:"varint,9,opt,name=timeout_block_height,json=timeoutBlockHeight,proto3" json:"timeout_block_height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReverseSwapInfo) Reset()         { *m = ReverseSwapInfo{} }
func (m *ReverseSwapInfo) String() string { return proto.CompactTextString(m) }
func (*ReverseSwapInfo) ProtoMessage()    {}
func (*ReverseSwapInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{4}
}

func (m *ReverseSwapInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReverseSwapInfo.Unmarshal(m, b)
}
func (m *ReverseSwapInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReverseSwapInfo.Marshal(b, m, deterministic)
}
func (m *ReverseSwapInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReverseSwapInfo.Merge(m, src)
}
func (m *ReverseSwapInfo) XXX_Size() int {
	return xxx_messageInfo_ReverseSwapInfo.Size(m)
}
func (m *ReverseSwapInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReverseSwapInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReverseSwapInfo proto.InternalMessageInfo

func (m *ReverseSwapInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ReverseSwapInfo) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *ReverseSwapInfo) GetPrivateKey() string {
	if m != nil {
		return m.PrivateKey
	}
	return ""
}

func (m *ReverseSwapInfo) GetPreimage() string {
	if m != nil {
		return m.Preimage
	}
	return ""
}

func (m *ReverseSwapInfo) GetRedeemScript() string {
	if m != nil {
		return m.RedeemScript
	}
	return ""
}

func (m *ReverseSwapInfo) GetInvoice() string {
	if m != nil {
		return m.Invoice
	}
	return ""
}

func (m *ReverseSwapInfo) GetClaimAddress() string {
	if m != nil {
		return m.ClaimAddress
	}
	return ""
}

func (m *ReverseSwapInfo) GetOnchainAmount() int64 {
	if m != nil {
		return m.OnchainAmount
	}
	return 0
}

func (m *ReverseSwapInfo) GetTimeoutBlockHeight() uint32 {
	if m != nil {
		return m.TimeoutBlockHeight
	}
	return 0
}

type GetSwapInfoResponse struct {
	Swap                 *SwapInfo        `protobuf:"bytes,1,opt,name=swap,proto3" json:"swap,omitempty"`
	ReverseSwap          *ReverseSwapInfo `protobuf:"bytes,2,opt,name=reverse_swap,json=reverseSwap,proto3" json:"reverse_swap,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetSwapInfoResponse) Reset()         { *m = GetSwapInfoResponse{} }
func (m *GetSwapInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetSwapInfoResponse) ProtoMessage()    {}
func (*GetSwapInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{5}
}

func (m *GetSwapInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSwapInfoResponse.Unmarshal(m, b)
}
func (m *GetSwapInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSwapInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetSwapInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSwapInfoResponse.Merge(m, src)
}
func (m *GetSwapInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetSwapInfoResponse.Size(m)
}
func (m *GetSwapInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSwapInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSwapInfoResponse proto.InternalMessageInfo

func (m *GetSwapInfoResponse) GetSwap() *SwapInfo {
	if m != nil {
		return m.Swap
	}
	return nil
}

func (m *GetSwapInfoResponse) GetReverseSwap() *ReverseSwapInfo {
	if m != nil {
		return m.ReverseSwap
	}
	return nil
}

type MinerFees struct {
	Normal               uint32   `protobuf:"varint,1,opt,name=normal,proto3" json:"normal,omitempty"`
	Reverse              uint32   `protobuf:"varint,2,opt,name=reverse,proto3" json:"reverse,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MinerFees) Reset()         { *m = MinerFees{} }
func (m *MinerFees) String() string { return proto.CompactTextString(m) }
func (*MinerFees) ProtoMessage()    {}
func (*MinerFees) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{6}
}

func (m *MinerFees) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MinerFees.Unmarshal(m, b)
}
func (m *MinerFees) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MinerFees.Marshal(b, m, deterministic)
}
func (m *MinerFees) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MinerFees.Merge(m, src)
}
func (m *MinerFees) XXX_Size() int {
	return xxx_messageInfo_MinerFees.Size(m)
}
func (m *MinerFees) XXX_DiscardUnknown() {
	xxx_messageInfo_MinerFees.DiscardUnknown(m)
}

var xxx_messageInfo_MinerFees proto.InternalMessageInfo

func (m *MinerFees) GetNormal() uint32 {
	if m != nil {
		return m.Normal
	}
	return 0
}

func (m *MinerFees) GetReverse() uint32 {
	if m != nil {
		return m.Reverse
	}
	return 0
}

type Fees struct {
	Percentage           float32    `protobuf:"fixed32,1,opt,name=percentage,proto3" json:"percentage,omitempty"`
	Miner                *MinerFees `protobuf:"bytes,2,opt,name=miner,proto3" json:"miner,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Fees) Reset()         { *m = Fees{} }
func (m *Fees) String() string { return proto.CompactTextString(m) }
func (*Fees) ProtoMessage()    {}
func (*Fees) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{7}
}

func (m *Fees) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Fees.Unmarshal(m, b)
}
func (m *Fees) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Fees.Marshal(b, m, deterministic)
}
func (m *Fees) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Fees.Merge(m, src)
}
func (m *Fees) XXX_Size() int {
	return xxx_messageInfo_Fees.Size(m)
}
func (m *Fees) XXX_DiscardUnknown() {
	xxx_messageInfo_Fees.DiscardUnknown(m)
}

var xxx_messageInfo_Fees proto.InternalMessageInfo

func (m *Fees) GetPercentage() float32 {
	if m != nil {
		return m.Percentage
	}
	return 0
}

func (m *Fees) GetMiner() *MinerFees {
	if m != nil {
		return m.Miner
	}
	return nil
}

type Limits struct {
	Minimal              int64    `protobuf:"varint,1,opt,name=minimal,proto3" json:"minimal,omitempty"`
	Maximal              int64    `protobuf:"varint,2,opt,name=maximal,proto3" json:"maximal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Limits) Reset()         { *m = Limits{} }
func (m *Limits) String() string { return proto.CompactTextString(m) }
func (*Limits) ProtoMessage()    {}
func (*Limits) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{8}
}

func (m *Limits) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Limits.Unmarshal(m, b)
}
func (m *Limits) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Limits.Marshal(b, m, deterministic)
}
func (m *Limits) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Limits.Merge(m, src)
}
func (m *Limits) XXX_Size() int {
	return xxx_messageInfo_Limits.Size(m)
}
func (m *Limits) XXX_DiscardUnknown() {
	xxx_messageInfo_Limits.DiscardUnknown(m)
}

var xxx_messageInfo_Limits proto.InternalMessageInfo

func (m *Limits) GetMinimal() int64 {
	if m != nil {
		return m.Minimal
	}
	return 0
}

func (m *Limits) GetMaximal() int64 {
	if m != nil {
		return m.Maximal
	}
	return 0
}

type GetServiceInfoRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetServiceInfoRequest) Reset()         { *m = GetServiceInfoRequest{} }
func (m *GetServiceInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetServiceInfoRequest) ProtoMessage()    {}
func (*GetServiceInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{9}
}

func (m *GetServiceInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetServiceInfoRequest.Unmarshal(m, b)
}
func (m *GetServiceInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetServiceInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetServiceInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetServiceInfoRequest.Merge(m, src)
}
func (m *GetServiceInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetServiceInfoRequest.Size(m)
}
func (m *GetServiceInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetServiceInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetServiceInfoRequest proto.InternalMessageInfo

type GetServiceInfoResponse struct {
	Fees                 *Fees    `protobuf:"bytes,1,opt,name=fees,proto3" json:"fees,omitempty"`
	Limits               *Limits  `protobuf:"bytes,2,opt,name=limits,proto3" json:"limits,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetServiceInfoResponse) Reset()         { *m = GetServiceInfoResponse{} }
func (m *GetServiceInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetServiceInfoResponse) ProtoMessage()    {}
func (*GetServiceInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{10}
}

func (m *GetServiceInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetServiceInfoResponse.Unmarshal(m, b)
}
func (m *GetServiceInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetServiceInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetServiceInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetServiceInfoResponse.Merge(m, src)
}
func (m *GetServiceInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetServiceInfoResponse.Size(m)
}
func (m *GetServiceInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetServiceInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetServiceInfoResponse proto.InternalMessageInfo

func (m *GetServiceInfoResponse) GetFees() *Fees {
	if m != nil {
		return m.Fees
	}
	return nil
}

func (m *GetServiceInfoResponse) GetLimits() *Limits {
	if m != nil {
		return m.Limits
	}
	return nil
}

type DepositRequest struct {
	InboundLiquidity     uint32   `protobuf:"varint,1,opt,name=inbound_liquidity,json=inboundLiquidity,proto3" json:"inbound_liquidity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DepositRequest) Reset()         { *m = DepositRequest{} }
func (m *DepositRequest) String() string { return proto.CompactTextString(m) }
func (*DepositRequest) ProtoMessage()    {}
func (*DepositRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{11}
}

func (m *DepositRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DepositRequest.Unmarshal(m, b)
}
func (m *DepositRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DepositRequest.Marshal(b, m, deterministic)
}
func (m *DepositRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DepositRequest.Merge(m, src)
}
func (m *DepositRequest) XXX_Size() int {
	return xxx_messageInfo_DepositRequest.Size(m)
}
func (m *DepositRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DepositRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DepositRequest proto.InternalMessageInfo

func (m *DepositRequest) GetInboundLiquidity() uint32 {
	if m != nil {
		return m.InboundLiquidity
	}
	return 0
}

type DepositResponse struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	TimeoutBlockHeight   uint32   `protobuf:"varint,2,opt,name=timeout_block_height,json=timeoutBlockHeight,proto3" json:"timeout_block_height,omitempty"`
	Fees                 *Fees    `protobuf:"bytes,3,opt,name=fees,proto3" json:"fees,omitempty"`
	Limits               *Limits  `protobuf:"bytes,4,opt,name=limits,proto3" json:"limits,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DepositResponse) Reset()         { *m = DepositResponse{} }
func (m *DepositResponse) String() string { return proto.CompactTextString(m) }
func (*DepositResponse) ProtoMessage()    {}
func (*DepositResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{12}
}

func (m *DepositResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DepositResponse.Unmarshal(m, b)
}
func (m *DepositResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DepositResponse.Marshal(b, m, deterministic)
}
func (m *DepositResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DepositResponse.Merge(m, src)
}
func (m *DepositResponse) XXX_Size() int {
	return xxx_messageInfo_DepositResponse.Size(m)
}
func (m *DepositResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DepositResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DepositResponse proto.InternalMessageInfo

func (m *DepositResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *DepositResponse) GetTimeoutBlockHeight() uint32 {
	if m != nil {
		return m.TimeoutBlockHeight
	}
	return 0
}

func (m *DepositResponse) GetFees() *Fees {
	if m != nil {
		return m.Fees
	}
	return nil
}

func (m *DepositResponse) GetLimits() *Limits {
	if m != nil {
		return m.Limits
	}
	return nil
}

type CreateSwapRequest struct {
	Amount               int64    `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSwapRequest) Reset()         { *m = CreateSwapRequest{} }
func (m *CreateSwapRequest) String() string { return proto.CompactTextString(m) }
func (*CreateSwapRequest) ProtoMessage()    {}
func (*CreateSwapRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{13}
}

func (m *CreateSwapRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSwapRequest.Unmarshal(m, b)
}
func (m *CreateSwapRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSwapRequest.Marshal(b, m, deterministic)
}
func (m *CreateSwapRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSwapRequest.Merge(m, src)
}
func (m *CreateSwapRequest) XXX_Size() int {
	return xxx_messageInfo_CreateSwapRequest.Size(m)
}
func (m *CreateSwapRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSwapRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSwapRequest proto.InternalMessageInfo

func (m *CreateSwapRequest) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type CreateSwapResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	ExpectedAmount       int64    `protobuf:"varint,3,opt,name=expected_amount,json=expectedAmount,proto3" json:"expected_amount,omitempty"`
	Bip21                string   `protobuf:"bytes,4,opt,name=bip21,proto3" json:"bip21,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSwapResponse) Reset()         { *m = CreateSwapResponse{} }
func (m *CreateSwapResponse) String() string { return proto.CompactTextString(m) }
func (*CreateSwapResponse) ProtoMessage()    {}
func (*CreateSwapResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{14}
}

func (m *CreateSwapResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSwapResponse.Unmarshal(m, b)
}
func (m *CreateSwapResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSwapResponse.Marshal(b, m, deterministic)
}
func (m *CreateSwapResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSwapResponse.Merge(m, src)
}
func (m *CreateSwapResponse) XXX_Size() int {
	return xxx_messageInfo_CreateSwapResponse.Size(m)
}
func (m *CreateSwapResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSwapResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSwapResponse proto.InternalMessageInfo

func (m *CreateSwapResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateSwapResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *CreateSwapResponse) GetExpectedAmount() int64 {
	if m != nil {
		return m.ExpectedAmount
	}
	return 0
}

func (m *CreateSwapResponse) GetBip21() string {
	if m != nil {
		return m.Bip21
	}
	return ""
}

type CreateChannelRequest struct {
	Amount               int64    `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	InboundLiquidity     uint32   `protobuf:"varint,2,opt,name=inbound_liquidity,json=inboundLiquidity,proto3" json:"inbound_liquidity,omitempty"`
	Private              bool     `protobuf:"varint,3,opt,name=private,proto3" json:"private,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateChannelRequest) Reset()         { *m = CreateChannelRequest{} }
func (m *CreateChannelRequest) String() string { return proto.CompactTextString(m) }
func (*CreateChannelRequest) ProtoMessage()    {}
func (*CreateChannelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{15}
}

func (m *CreateChannelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateChannelRequest.Unmarshal(m, b)
}
func (m *CreateChannelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateChannelRequest.Marshal(b, m, deterministic)
}
func (m *CreateChannelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateChannelRequest.Merge(m, src)
}
func (m *CreateChannelRequest) XXX_Size() int {
	return xxx_messageInfo_CreateChannelRequest.Size(m)
}
func (m *CreateChannelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateChannelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateChannelRequest proto.InternalMessageInfo

func (m *CreateChannelRequest) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *CreateChannelRequest) GetInboundLiquidity() uint32 {
	if m != nil {
		return m.InboundLiquidity
	}
	return 0
}

func (m *CreateChannelRequest) GetPrivate() bool {
	if m != nil {
		return m.Private
	}
	return false
}

type CreateReverseSwapRequest struct {
	Amount               int64    `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	AcceptZeroConf       bool     `protobuf:"varint,3,opt,name=accept_zero_conf,json=acceptZeroConf,proto3" json:"accept_zero_conf,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateReverseSwapRequest) Reset()         { *m = CreateReverseSwapRequest{} }
func (m *CreateReverseSwapRequest) String() string { return proto.CompactTextString(m) }
func (*CreateReverseSwapRequest) ProtoMessage()    {}
func (*CreateReverseSwapRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{16}
}

func (m *CreateReverseSwapRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateReverseSwapRequest.Unmarshal(m, b)
}
func (m *CreateReverseSwapRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateReverseSwapRequest.Marshal(b, m, deterministic)
}
func (m *CreateReverseSwapRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateReverseSwapRequest.Merge(m, src)
}
func (m *CreateReverseSwapRequest) XXX_Size() int {
	return xxx_messageInfo_CreateReverseSwapRequest.Size(m)
}
func (m *CreateReverseSwapRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateReverseSwapRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateReverseSwapRequest proto.InternalMessageInfo

func (m *CreateReverseSwapRequest) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *CreateReverseSwapRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *CreateReverseSwapRequest) GetAcceptZeroConf() bool {
	if m != nil {
		return m.AcceptZeroConf
	}
	return false
}

type CreateReverseSwapResponse struct {
	Id                 string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RoutingFeeMilliSat uint32 `protobuf:"varint,2,opt,name=routing_fee_milli_sat,json=routingFeeMilliSat,proto3" json:"routing_fee_milli_sat,omitempty"`
	// Only populated when 0-conf is accepted
	ClaimTransactionId   string   `protobuf:"bytes,3,opt,name=claim_transaction_id,json=claimTransactionId,proto3" json:"claim_transaction_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateReverseSwapResponse) Reset()         { *m = CreateReverseSwapResponse{} }
func (m *CreateReverseSwapResponse) String() string { return proto.CompactTextString(m) }
func (*CreateReverseSwapResponse) ProtoMessage()    {}
func (*CreateReverseSwapResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{17}
}

func (m *CreateReverseSwapResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateReverseSwapResponse.Unmarshal(m, b)
}
func (m *CreateReverseSwapResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateReverseSwapResponse.Marshal(b, m, deterministic)
}
func (m *CreateReverseSwapResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateReverseSwapResponse.Merge(m, src)
}
func (m *CreateReverseSwapResponse) XXX_Size() int {
	return xxx_messageInfo_CreateReverseSwapResponse.Size(m)
}
func (m *CreateReverseSwapResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateReverseSwapResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateReverseSwapResponse proto.InternalMessageInfo

func (m *CreateReverseSwapResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateReverseSwapResponse) GetRoutingFeeMilliSat() uint32 {
	if m != nil {
		return m.RoutingFeeMilliSat
	}
	return 0
}

func (m *CreateReverseSwapResponse) GetClaimTransactionId() string {
	if m != nil {
		return m.ClaimTransactionId
	}
	return ""
}

func init() {
	proto.RegisterType((*GetInfoRequest)(nil), "boltzrpc.GetInfoRequest")
	proto.RegisterType((*GetInfoResponse)(nil), "boltzrpc.GetInfoResponse")
	proto.RegisterType((*GetSwapInfoRequest)(nil), "boltzrpc.GetSwapInfoRequest")
	proto.RegisterType((*SwapInfo)(nil), "boltzrpc.SwapInfo")
	proto.RegisterType((*ReverseSwapInfo)(nil), "boltzrpc.ReverseSwapInfo")
	proto.RegisterType((*GetSwapInfoResponse)(nil), "boltzrpc.GetSwapInfoResponse")
	proto.RegisterType((*MinerFees)(nil), "boltzrpc.MinerFees")
	proto.RegisterType((*Fees)(nil), "boltzrpc.Fees")
	proto.RegisterType((*Limits)(nil), "boltzrpc.Limits")
	proto.RegisterType((*GetServiceInfoRequest)(nil), "boltzrpc.GetServiceInfoRequest")
	proto.RegisterType((*GetServiceInfoResponse)(nil), "boltzrpc.GetServiceInfoResponse")
	proto.RegisterType((*DepositRequest)(nil), "boltzrpc.DepositRequest")
	proto.RegisterType((*DepositResponse)(nil), "boltzrpc.DepositResponse")
	proto.RegisterType((*CreateSwapRequest)(nil), "boltzrpc.CreateSwapRequest")
	proto.RegisterType((*CreateSwapResponse)(nil), "boltzrpc.CreateSwapResponse")
	proto.RegisterType((*CreateChannelRequest)(nil), "boltzrpc.CreateChannelRequest")
	proto.RegisterType((*CreateReverseSwapRequest)(nil), "boltzrpc.CreateReverseSwapRequest")
	proto.RegisterType((*CreateReverseSwapResponse)(nil), "boltzrpc.CreateReverseSwapResponse")
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor_77a6da22d6a3feb1) }

var fileDescriptor_77a6da22d6a3feb1 = []byte{
	// 979 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x56, 0xeb, 0x6e, 0xdc, 0x44,
	0x14, 0xd6, 0x7a, 0xef, 0x67, 0x2f, 0x49, 0x27, 0x17, 0x9c, 0xa5, 0x97, 0xc5, 0xa1, 0xb0, 0xa8,
	0x52, 0x44, 0x97, 0xbf, 0x6d, 0xa5, 0x36, 0xa8, 0xa1, 0xd0, 0x48, 0xe0, 0xf0, 0x0b, 0x21, 0x59,
	0x5e, 0xfb, 0x6c, 0x32, 0xaa, 0x3d, 0xe3, 0x8e, 0xc7, 0x4b, 0x53, 0xc4, 0x3b, 0xf0, 0x04, 0xbc,
	0x00, 0x7f, 0x90, 0x78, 0x05, 0x1e, 0x0c, 0x79, 0x3c, 0x5e, 0x5f, 0xb2, 0x4b, 0x10, 0xff, 0xf8,
	0xb7, 0xe7, 0xfb, 0xce, 0xcc, 0x9c, 0xf3, 0x9d, 0xcb, 0x1a, 0xfa, 0x22, 0xf2, 0x4e, 0x22, 0xc1,
	0x25, 0x27, 0xbd, 0x05, 0x0f, 0xe4, 0x7b, 0x11, 0x79, 0xd6, 0x2e, 0x8c, 0xcf, 0x50, 0xbe, 0x62,
	0x4b, 0x6e, 0xe3, 0xdb, 0x04, 0x63, 0x69, 0xfd, 0xd5, 0x80, 0x9d, 0x35, 0x14, 0x47, 0x9c, 0xc5,
	0x48, 0x0e, 0xa1, 0x13, 0x5f, 0x87, 0x0b, 0x1e, 0x98, 0x8d, 0x69, 0x63, 0xd6, 0xb7, 0xb5, 0x45,
	0xee, 0x01, 0x04, 0xcc, 0x77, 0xa2, 0x64, 0xf1, 0x06, 0xaf, 0x4d, 0x43, 0x71, 0xfd, 0x80, 0xf9,
	0xdf, 0x2a, 0x80, 0x7c, 0x04, 0xc3, 0x45, 0xc0, 0xbd, 0x37, 0xce, 0x15, 0xd2, 0xcb, 0x2b, 0x69,
	0x36, 0xa7, 0x8d, 0xd9, 0xc8, 0x1e, 0x28, 0xec, 0x2b, 0x05, 0x91, 0x63, 0x18, 0x45, 0xc8, 0x7c,
	0xca, 0x2e, 0x9d, 0xf8, 0x27, 0x37, 0x8a, 0xcd, 0xd6, 0xb4, 0x39, 0xeb, 0xdb, 0x43, 0x0d, 0x5e,
	0xa4, 0x18, 0x99, 0xc3, 0x41, 0xee, 0x24, 0x70, 0x85, 0x22, 0x46, 0xed, 0xdc, 0x56, 0xce, 0x7b,
	0x9a, 0xb4, 0x33, 0x4e, 0x9d, 0xb1, 0x3e, 0x06, 0x72, 0x86, 0x32, 0xfd, 0x5d, 0x4a, 0x8e, 0x8c,
	0xc1, 0xa0, 0xbe, 0x4e, 0xc2, 0xa0, 0xbe, 0xf5, 0x87, 0x01, 0xbd, 0xdc, 0xa7, 0x4e, 0xaa, 0xac,
	0xa5, 0x2b, 0x93, 0x58, 0x67, 0xa6, 0x2d, 0xf2, 0x00, 0x06, 0x91, 0xa0, 0x2b, 0x57, 0xa2, 0x93,
	0xa6, 0xdd, 0x54, 0x24, 0x68, 0xe8, 0x1b, 0xbc, 0x26, 0x13, 0xe8, 0x45, 0x02, 0x69, 0xe8, 0x5e,
	0xa2, 0xd9, 0x52, 0xec, 0xda, 0x4e, 0x13, 0x16, 0xe8, 0x23, 0x86, 0x4e, 0xec, 0x09, 0x1a, 0x49,
	0xb3, 0xad, 0x1c, 0x86, 0x19, 0x78, 0xa1, 0x30, 0x62, 0x42, 0x97, 0xb2, 0x15, 0xa7, 0x1e, 0x9a,
	0x1d, 0x45, 0xe7, 0x26, 0x79, 0x08, 0xe3, 0x54, 0xbd, 0x24, 0x72, 0x5c, 0xdf, 0x17, 0x18, 0xc7,
	0x66, 0x57, 0x39, 0x8c, 0x32, 0xf4, 0x79, 0x06, 0x92, 0x4f, 0x61, 0x07, 0xdf, 0x45, 0xe8, 0x49,
	0xf4, 0x1d, 0x37, 0xe4, 0x09, 0x93, 0x66, 0x6f, 0xda, 0x98, 0x35, 0xed, 0x71, 0x0e, 0x3f, 0x57,
	0x28, 0xf9, 0x1c, 0xf6, 0x25, 0x0d, 0x91, 0x27, 0xd2, 0xa9, 0x94, 0xaa, 0xaf, 0x4a, 0x45, 0x34,
	0xf7, 0xa2, 0xa8, 0x98, 0xf5, 0xa7, 0x01, 0x3b, 0x25, 0xa5, 0xff, 0x37, 0xca, 0x1d, 0xc3, 0xc8,
	0x0b, 0x5c, 0x1a, 0xd6, 0x84, 0x1b, 0x2a, 0x30, 0xd7, 0xed, 0x21, 0x8c, 0x39, 0xf3, 0xae, 0x5c,
	0xca, 0xaa, 0xb2, 0x8d, 0x34, 0xfa, 0x9f, 0x55, 0xfb, 0x19, 0xf6, 0x2a, 0xed, 0xa8, 0x07, 0xeb,
	0x13, 0x68, 0xa5, 0x9d, 0xac, 0xa4, 0x1b, 0xcc, 0xc9, 0x49, 0x3e, 0x97, 0x27, 0x6b, 0x4f, 0xc5,
	0x93, 0x27, 0x30, 0x2c, 0x77, 0xbe, 0x92, 0x75, 0x30, 0x3f, 0x2a, 0xfc, 0x6b, 0x15, 0xb1, 0x07,
	0xa2, 0x00, 0xac, 0xa7, 0xd0, 0x3f, 0xa7, 0x0c, 0xc5, 0x4b, 0xc4, 0x38, 0xad, 0x0d, 0xe3, 0x22,
	0x74, 0xb3, 0x59, 0x1e, 0xd9, 0xda, 0x4a, 0x95, 0xd3, 0x67, 0xd4, 0xed, 0x23, 0x3b, 0x37, 0xad,
	0xef, 0xa0, 0xa5, 0x4e, 0xde, 0x07, 0x88, 0x50, 0x78, 0xc8, 0x64, 0x5a, 0x9e, 0xf4, 0xb4, 0x61,
	0x97, 0x10, 0xf2, 0x19, 0xb4, 0xc3, 0xf4, 0x19, 0x1d, 0xdd, 0x5e, 0x11, 0xdd, 0xfa, 0x75, 0x3b,
	0xf3, 0xb0, 0x9e, 0x40, 0xe7, 0x35, 0x0d, 0xa9, 0x8c, 0xd3, 0x67, 0x43, 0xca, 0x68, 0x1e, 0x4f,
	0xd3, 0xce, 0x4d, 0xc5, 0xb8, 0xef, 0x14, 0x63, 0x68, 0x26, 0x33, 0xad, 0x0f, 0xe0, 0x20, 0x15,
	0x13, 0xc5, 0x8a, 0x7a, 0x58, 0xde, 0x5d, 0x4b, 0x38, 0xac, 0x13, 0x5a, 0x68, 0x0b, 0x5a, 0x4b,
	0xc4, 0x58, 0x0b, 0x3d, 0x2e, 0x42, 0x53, 0x51, 0x29, 0x8e, 0xcc, 0xa0, 0x13, 0xa8, 0xa0, 0x74,
	0x02, 0xbb, 0x85, 0x57, 0x16, 0xac, 0xad, 0x79, 0xeb, 0x29, 0x8c, 0xbf, 0xc4, 0x88, 0xc7, 0x54,
	0xe6, 0x8b, 0xe5, 0x11, 0xdc, 0xa1, 0x6c, 0xc1, 0x13, 0xe6, 0x3b, 0x01, 0x7d, 0x9b, 0x50, 0x9f,
	0xca, 0x6b, 0x2d, 0xf0, 0xae, 0x26, 0x5e, 0xe7, 0xb8, 0xf5, 0x7b, 0x03, 0x76, 0xd6, 0xe7, 0x75,
	0x80, 0x26, 0x74, 0xf3, 0xc6, 0xcc, 0xe6, 0x28, 0x37, 0xb7, 0x36, 0x9b, 0xb1, 0xad, 0xd9, 0xd6,
	0xc9, 0x36, 0xff, 0x55, 0xb2, 0xad, 0x5b, 0x92, 0x7d, 0x04, 0x77, 0x4e, 0x05, 0xba, 0x52, 0xf5,
	0x52, 0x9e, 0xef, 0x21, 0x74, 0xf4, 0x80, 0x64, 0x55, 0xd3, 0x96, 0xf5, 0x0b, 0x90, 0xb2, 0xb3,
	0x4e, 0xae, 0xbe, 0x1f, 0x4a, 0xc9, 0x1a, 0xd5, 0x64, 0x37, 0x2c, 0xae, 0xe6, 0xc6, 0xc5, 0xb5,
	0x0f, 0xed, 0x05, 0x8d, 0xe6, 0x8f, 0xf5, 0x9a, 0xc8, 0x0c, 0x2b, 0x81, 0xfd, 0xec, 0xf9, 0xd3,
	0x2b, 0x97, 0x31, 0x0c, 0x6e, 0x09, 0x77, 0x73, 0xd9, 0x8c, 0xcd, 0x65, 0x4b, 0xa3, 0xd6, 0xab,
	0x4a, 0xc5, 0xd4, 0xb3, 0x73, 0xd3, 0x5a, 0x81, 0x99, 0x3d, 0x5b, 0x1a, 0xc3, 0xdb, 0x9e, 0xde,
	0xae, 0xc1, 0x0c, 0x76, 0x5d, 0xcf, 0xc3, 0x48, 0x3a, 0xef, 0x51, 0x70, 0xc7, 0xe3, 0x6c, 0xa9,
	0x1f, 0x1c, 0x67, 0xf8, 0x0f, 0x28, 0xf8, 0x29, 0x67, 0x4b, 0xeb, 0xd7, 0x06, 0x1c, 0x6d, 0x78,
	0x78, 0x8b, 0xea, 0x8f, 0xe1, 0x40, 0xf0, 0x44, 0xa6, 0x7f, 0xa3, 0x4b, 0x44, 0x27, 0xa4, 0x41,
	0x40, 0x9d, 0xd8, 0x5d, 0x77, 0x92, 0x26, 0x5f, 0x22, 0x9e, 0xa7, 0xd4, 0x85, 0xab, 0x16, 0x5d,
	0xb6, 0x34, 0xa5, 0x70, 0x59, 0xec, 0x7a, 0x92, 0x72, 0xe6, 0x50, 0x5f, 0x6f, 0x6e, 0xa2, 0xb8,
	0xef, 0x0b, 0xea, 0x95, 0x3f, 0xff, 0xad, 0x05, 0xed, 0x17, 0x69, 0x27, 0x91, 0x67, 0xd0, 0xd5,
	0xdf, 0x11, 0xc4, 0x2c, 0x9a, 0xab, 0xfa, 0xb5, 0x31, 0x39, 0xda, 0xc0, 0xe8, 0xf0, 0xbf, 0x86,
	0x41, 0x69, 0x65, 0x92, 0xbb, 0x15, 0xcf, 0xda, 0x1f, 0xfb, 0xe4, 0xde, 0x16, 0x56, 0xdf, 0x75,
	0xa1, 0x3e, 0x73, 0x4a, 0x8b, 0x81, 0x3c, 0xa8, 0x1e, 0xb8, 0xb1, 0x4b, 0x26, 0xd3, 0xed, 0x0e,
	0xfa, 0xd2, 0x67, 0xd0, 0xd5, 0x53, 0x5c, 0x4e, 0xb0, 0xba, 0x18, 0xca, 0x09, 0xd6, 0x47, 0xfe,
	0x0c, 0xa0, 0x98, 0x15, 0xf2, 0x61, 0xe1, 0x78, 0x63, 0xdc, 0x26, 0x77, 0x37, 0x93, 0xfa, 0xa2,
	0x73, 0x18, 0x55, 0xba, 0x9e, 0xdc, 0xaf, 0xbb, 0x57, 0xc7, 0xe1, 0x96, 0xeb, 0x7e, 0xcc, 0x07,
	0xbe, 0xd4, 0x54, 0xc4, 0xaa, 0x1f, 0xb9, 0xd9, 0xea, 0x93, 0xe3, 0x7f, 0xf4, 0xc9, 0x6e, 0x5f,
	0x74, 0xd4, 0x27, 0xe8, 0x17, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0xd9, 0xea, 0x04, 0x44, 0x8f,
	0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BoltzClient is the client API for Boltz service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BoltzClient interface {
	GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoResponse, error)
	GetSwapInfo(ctx context.Context, in *GetSwapInfoRequest, opts ...grpc.CallOption) (*GetSwapInfoResponse, error)
	GetServiceInfo(ctx context.Context, in *GetServiceInfoRequest, opts ...grpc.CallOption) (*GetServiceInfoResponse, error)
	Deposit(ctx context.Context, in *DepositRequest, opts ...grpc.CallOption) (*DepositResponse, error)
	CreateSwap(ctx context.Context, in *CreateSwapRequest, opts ...grpc.CallOption) (*CreateSwapResponse, error)
	CreateChannel(ctx context.Context, in *CreateChannelRequest, opts ...grpc.CallOption) (*CreateSwapResponse, error)
	CreateReverseSwap(ctx context.Context, in *CreateReverseSwapRequest, opts ...grpc.CallOption) (*CreateReverseSwapResponse, error)
}

type boltzClient struct {
	cc *grpc.ClientConn
}

func NewBoltzClient(cc *grpc.ClientConn) BoltzClient {
	return &boltzClient{cc}
}

func (c *boltzClient) GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoResponse, error) {
	out := new(GetInfoResponse)
	err := c.cc.Invoke(ctx, "/boltzrpc.Boltz/GetInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boltzClient) GetSwapInfo(ctx context.Context, in *GetSwapInfoRequest, opts ...grpc.CallOption) (*GetSwapInfoResponse, error) {
	out := new(GetSwapInfoResponse)
	err := c.cc.Invoke(ctx, "/boltzrpc.Boltz/GetSwapInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boltzClient) GetServiceInfo(ctx context.Context, in *GetServiceInfoRequest, opts ...grpc.CallOption) (*GetServiceInfoResponse, error) {
	out := new(GetServiceInfoResponse)
	err := c.cc.Invoke(ctx, "/boltzrpc.Boltz/GetServiceInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boltzClient) Deposit(ctx context.Context, in *DepositRequest, opts ...grpc.CallOption) (*DepositResponse, error) {
	out := new(DepositResponse)
	err := c.cc.Invoke(ctx, "/boltzrpc.Boltz/Deposit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boltzClient) CreateSwap(ctx context.Context, in *CreateSwapRequest, opts ...grpc.CallOption) (*CreateSwapResponse, error) {
	out := new(CreateSwapResponse)
	err := c.cc.Invoke(ctx, "/boltzrpc.Boltz/CreateSwap", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boltzClient) CreateChannel(ctx context.Context, in *CreateChannelRequest, opts ...grpc.CallOption) (*CreateSwapResponse, error) {
	out := new(CreateSwapResponse)
	err := c.cc.Invoke(ctx, "/boltzrpc.Boltz/CreateChannel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boltzClient) CreateReverseSwap(ctx context.Context, in *CreateReverseSwapRequest, opts ...grpc.CallOption) (*CreateReverseSwapResponse, error) {
	out := new(CreateReverseSwapResponse)
	err := c.cc.Invoke(ctx, "/boltzrpc.Boltz/CreateReverseSwap", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BoltzServer is the server API for Boltz service.
type BoltzServer interface {
	GetInfo(context.Context, *GetInfoRequest) (*GetInfoResponse, error)
	GetSwapInfo(context.Context, *GetSwapInfoRequest) (*GetSwapInfoResponse, error)
	GetServiceInfo(context.Context, *GetServiceInfoRequest) (*GetServiceInfoResponse, error)
	Deposit(context.Context, *DepositRequest) (*DepositResponse, error)
	CreateSwap(context.Context, *CreateSwapRequest) (*CreateSwapResponse, error)
	CreateChannel(context.Context, *CreateChannelRequest) (*CreateSwapResponse, error)
	CreateReverseSwap(context.Context, *CreateReverseSwapRequest) (*CreateReverseSwapResponse, error)
}

func RegisterBoltzServer(s *grpc.Server, srv BoltzServer) {
	s.RegisterService(&_Boltz_serviceDesc, srv)
}

func _Boltz_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoltzServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/boltzrpc.Boltz/GetInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoltzServer).GetInfo(ctx, req.(*GetInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Boltz_GetSwapInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSwapInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoltzServer).GetSwapInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/boltzrpc.Boltz/GetSwapInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoltzServer).GetSwapInfo(ctx, req.(*GetSwapInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Boltz_GetServiceInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServiceInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoltzServer).GetServiceInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/boltzrpc.Boltz/GetServiceInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoltzServer).GetServiceInfo(ctx, req.(*GetServiceInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Boltz_Deposit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DepositRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoltzServer).Deposit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/boltzrpc.Boltz/Deposit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoltzServer).Deposit(ctx, req.(*DepositRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Boltz_CreateSwap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSwapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoltzServer).CreateSwap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/boltzrpc.Boltz/CreateSwap",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoltzServer).CreateSwap(ctx, req.(*CreateSwapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Boltz_CreateChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoltzServer).CreateChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/boltzrpc.Boltz/CreateChannel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoltzServer).CreateChannel(ctx, req.(*CreateChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Boltz_CreateReverseSwap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReverseSwapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoltzServer).CreateReverseSwap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/boltzrpc.Boltz/CreateReverseSwap",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoltzServer).CreateReverseSwap(ctx, req.(*CreateReverseSwapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Boltz_serviceDesc = grpc.ServiceDesc{
	ServiceName: "boltzrpc.Boltz",
	HandlerType: (*BoltzServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfo",
			Handler:    _Boltz_GetInfo_Handler,
		},
		{
			MethodName: "GetSwapInfo",
			Handler:    _Boltz_GetSwapInfo_Handler,
		},
		{
			MethodName: "GetServiceInfo",
			Handler:    _Boltz_GetServiceInfo_Handler,
		},
		{
			MethodName: "Deposit",
			Handler:    _Boltz_Deposit_Handler,
		},
		{
			MethodName: "CreateSwap",
			Handler:    _Boltz_CreateSwap_Handler,
		},
		{
			MethodName: "CreateChannel",
			Handler:    _Boltz_CreateChannel_Handler,
		},
		{
			MethodName: "CreateReverseSwap",
			Handler:    _Boltz_CreateReverseSwap_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}
