name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: CI

    strategy:
      matrix:
        platform: [ ubuntu-latest ]
        go-version: [ 1.24.x ]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache-workspaces: |
           ./internal/lightning/lib/bolt12
           ./lwk

      - name: Build
        run: make build

      - name: Unit Tests
        run: make unit

      - name: Start Regtest
        env:
          COMPOSE_PROFILES: ci
        run: chmod -R 777 regtest && make start-regtest

      - name: Backend logs
        if: failure()
        run: docker logs boltz-backend

      - name: Integration Tests
        run: make integration
